spring:
  jpa:
    hibernate:
      ddl-auto: create
  data:
    rest:
      base-path: /api
  h2:
    console: # URL jdbc:h2:mem:testdb
      enabled: true

management:
  info:
    git:
      mode: full
  security:
    enabled: false

endpoints:
  hypermedia:
    enabled: true

github:
  client:
    clientId: 944d19e231eb5763e1eb
    clientSecret: 8c5bb486748f1ca570e2d2f5acbda8fb00100275
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

google:
  client:
    clientId: 754362814981-sj5q55cc5buep7ncsq9d9t4l70tk0l50.apps.googleusercontent.com
    clientSecret: x0Xgl60nsw5GdHNkUq1OIfgP
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
      - openid
      - email
      - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
    preferTokenInfo: true

facebook:
  client:
    clientId: 1322246907867733
    clientSecret: 30b930bdbf817333732aee246f89bc38
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.http: DEBUG
    org.springframework.security.web.util.matcher: INFO





